# Generated by Django 5.1 on 2024-08-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=30)),
                ('speed', models.IntegerField()),
                ('glide', models.IntegerField()),
                ('turn', models.IntegerField()),
                ('fade', models.IntegerField()),
                ('image', models.ImageField(blank=True, default='default_disc.webp', null=True, upload_to='disc_images/')),
            ],
        ),
    ]
