# Generated by Django 5.1 on 2024-08-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='kind',
            field=models.CharField(default='Mid-Range', max_length=20),
            preserve_default=False,
        ),
    ]
