# Generated by Django 5.1 on 2024-08-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discs', '0002_disc_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disc',
            name='kind',
        ),
        migrations.AddField(
            model_name='disc',
            name='type',
            field=models.CharField(choices=[('Distance Driver', 'Distance Driver'), ('Fairway Driver', 'Fairway Driver'), ('Mid-Range', 'Mid-Range'), ('Putter', 'Putter')], default='Mid-Range', max_length=20),
            preserve_default=False,
        ),
    ]
