# Generated by Django 5.1 on 2024-09-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discs', '0003_remove_disc_kind_disc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disc',
            name='fade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='disc',
            name='glide',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='disc',
            name='speed',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='disc',
            name='turn',
            field=models.IntegerField(default=0),
        ),
    ]
