# Generated by Django 4.2.16 on 2024-09-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discs', '0004_alter_disc_fade_alter_disc_glide_alter_disc_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disc',
            name='image',
            field=models.ImageField(blank=True, default='default_disc.jpg', null=True, upload_to='disc_images/'),
        ),
    ]
